### ISSUE TITLE
Hardcoded Path to the Log File?

### ISSUE THREAD

**Issue by dsnvwlmnt** [flacostec/PoeCompass#1]
Seems like you might have hardcoded to the default installation path for PoE. I installed it in x86/Path of Exile instead of GGG and your program chokes on this:

![image](https://user-images.githubusercontent.com/14173022/59140415-b1366880-8951-11e9-9b7e-7f8a86c0729f.png)

Edit: I figured out you can edit the path in configuration.json, at least.

**Comment by Gadn** [comment]
You can just change the directory in configuration.json to make it work. It's in the top row.
